
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 16 21:52:59 PDT 2008
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER = 40;
  public static final int SEMI = 39;
  public static final int LPAREN = 31;
  public static final int INT = 16;
  public static final int PRINTLN = 21;
  public static final int MINUS = 29;
  public static final int STAR = 30;
  public static final int INSTANCEOF = 22;
  public static final int STATIC = 3;
  public static final int RPAREN = 32;
  public static final int AND = 27;
  public static final int LT = 25;
  public static final int COMMA = 38;
  public static final int BANG = 23;
  public static final int CLASS = 6;
  public static final int PLUS = 28;
  public static final int MAIN = 5;
  public static final int IF = 12;
  public static final int THIS = 8;
  public static final int ID = 41;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 15;
  public static final int RETURN = 10;
  public static final int TRUE = 17;
  public static final int SUPER = 9;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int VOID = 4;
  public static final int EQ = 24;
  public static final int LBRACK = 33;
  public static final int LBRACE = 35;
  public static final int ELSE = 13;
  public static final int RBRACK = 34;
  public static final int WHILE = 14;
  public static final int PUBLIC = 2;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 7;
  public static final int STRING = 20;
  public static final int FALSE = 18;
  public static final int GT = 26;
  public static final int LENGTH = 19;
}

